---
# only needed for readthedocs.io
site_name: 'Free Templates for AWS CloudFormation'
requirements_file: 'setup.txt'
theme: flatly
docs_dir: docs
pages:
- 'Home': 'index.md'
- 'EC2': 'ec2.md'
- 'ECS': 'ecs.md'
- 'Jenkins': 'jenkins.md'
- 'Operations': 'operations.md'
- 'Security': 'security.md'
- 'Static Website': 'static-website.md'
- 'VPC': 'vpc.md'
- 'WordPress': 'wordpress.md'
- 'Migrate to v6': 'migrate-v6.md'
- 'Migrate to v5': 'migrate-v5.md'
- 'Migrate to v4': 'migrate-v4.md'
