---
# only needed for readthedocs.io
site_name: 'Free Templates for AWS CloudFormation'
docs_dir: docs
theme: mkdocs
pages:
- Home: 'index.md'
- Templates:
  - 'EC2': 'ec2.md'
  - 'ECS': 'ecs.md'
  - 'Fargate': 'fargate.md'
  - 'Jenkins': 'jenkins.md'
  - 'Operations': 'operations.md'
  - 'Security': 'security.md'
  - 'State / Data': 'state.md'
  - 'Static Website': 'static-website.md'
  - 'VPC': 'vpc.md'
  - 'WordPress': 'wordpress.md'
- 'widdix CLI': 'cli.md'
- 'Migration Guides':
  - 'Migrate to v14': 'migrate-v14.md'
  - 'Migrate to v13': 'migrate-v13.md'
  - 'Migrate to v12': 'migrate-v12.md'
  - 'Migrate to v11': 'migrate-v11.md'
  - 'Migrate to v10': 'migrate-v10.md'
  - 'Migrate to v9': 'migrate-v9.md'
  - 'Migrate to v8': 'migrate-v8.md'
  - 'Migrate to v7': 'migrate-v7.md'
  - 'Migrate to v6': 'migrate-v6.md'
  - 'Migrate to v5': 'migrate-v5.md'
  - 'Migrate to v4': 'migrate-v4.md'
