name: Lint
on: [push, pull_request]
permissions:
  id-token: write
  contents: read
defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: ['hyperenv', 'medium']
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'actions/setup-python@v5'
      with:
        python-version: '3.12'
    - name: yamlllint
      run: |
        pip install yamllint==1.33.0
        yamllint .
    - name: cfn-lint
      run: |
        pip install cfn-lint==0.85.0
        cfn-lint -i W2001 W3045 W4002 W6001 W8003 E3026 -t '**/*.yaml'
    - name: license
      run: |
        find . -type f -name '*.yaml' -not -name '.readthedocs.yaml' | while read file; do set -ex && grep -q 'LICENSE-2.0' "$file"; done;
